### ISSUE TITLE
Do you know Delphi Package Manager?

### ISSUE THREAD

**Issue by luebbe** [digao-dalpiaz/CompInstall#1]
It looks a bit like Vincent and you are striving for similar goals. Maybe you could join forces?
https://github.com/DelphiPackageManager/DPM

**Comment by digao-dalpiaz** [comment]
Hi @luebbe 

Yes, I know DPM project, a very interesting project.

But my application is for use in a slightly different situation: you must incorporate CompInstall.exe into your component version, so when a programmer installs it, he just runs the application to install it.

DPM project aims to manage package installation in the Delphi IDE, almost like NuGet in Visual Studio (C#)

Thanks.
Best regards.
