### ISSUE TITLE
Error loading component definitions: Ini file not found

### ISSUE THREAD

**Issue by Fab8573** [digao-dalpiaz/CompInstall#5]
Hello,
I try to install it on my Delphi 12 but I get :
"Error loading component definitions: Ini file not found"

**Comment by Fab8573** [comment]
Ok it's need a "CompInstall.ini" for each component.
But it's doesn't detect my Delphi 12 : 
"Error loading component definitions: No version of Delphi installed or supported"

**Comment by Fab8573** [comment]
Ok add 12 in "CompInstall.ini" :
DelphiVersions=XE3;XE4;XE5;XE6;XE7;XE8;10;10.1;10.2;10.3;10.4;11;12

**Comment by Fab8573** [comment]
COMPILE COMPONENT...
Compile package DzNotepad (Win32)
Microsoft (R) Build Engine, version 4.8.9037.0
[Microsoft .NET Framework, Version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1009: File not found.
Commutateur : C:\Users\<user>\Documents\DzNotepad.dproj
**ERROR: Error compiling package DzNotepad (Exit Code 1)**

Because missing Synedit ?
But there is no Delphi 12 version here : 
https://github.com/SynEdit/SynEdit

**Comment by digao-dalpiaz** [comment]
Hello,

You may use this SynEdit PR with Delphi 12:
https://github.com/SynEdit/SynEdit/pull/202
